name: Lint Code

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: latest
        cache: npm
        cache-dependency-path: package-lock.json
    - name: Install Deps
      run: npm i
    - name: Lint code
      run: npm run lint